import os
import markdown as md
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail
from dotenv import load_dotenv

load_dotenv()

SENDGRID_API_KEY = os.getenv("SENDGRID_API_KEY")
FROM_EMAIL = os.getenv("SENDGRID_FROM_EMAIL", "noreply@weddingplannerai.com")


def send_report_email(to_email, report_markdown, event_date=""):
    """Convert the Markdown planning report to HTML and send via SendGrid."""
    if not SENDGRID_API_KEY:
        print("[Email] SENDGRID_API_KEY not set — skipping.")
        return False
    if not to_email:
        return False

    try:
        html_body = md.markdown(report_markdown, extensions=["tables", "fenced_code"])

        subject = "Your Wedding Planning Report"
        if event_date:
            subject += f" — {event_date}"

        styled_html = f"""
<html>
<body style="font-family: Georgia, serif; max-width: 700px; margin: 0 auto;
             padding: 32px 24px; color: #333; background: #fdf8f4;">
  <div style="border-left: 4px solid #7a4f3a; padding-left: 16px; margin-bottom: 28px;">
    <h1 style="color: #7a4f3a; margin: 0 0 6px;">Wedding Planner AI</h1>
    <p style="color: #999; margin: 0; font-size: 0.9rem;">
      Your personalised planning report is ready.
    </p>
  </div>
  <div style="background: #fff; border: 1px solid #e8ddd5; border-radius: 8px; padding: 28px;">
    {html_body}
  </div>
  <p style="color: #bbb; font-size: 0.8rem; margin-top: 24px; text-align: center;">
    Generated by Wedding Planner AI
  </p>
</body>
</html>
"""

        message = Mail(
            from_email=FROM_EMAIL,
            to_emails=to_email,
            subject=subject,
            html_content=styled_html,
        )

        sg = SendGridAPIClient(SENDGRID_API_KEY)
        sg.send(message)
        print(f"[Email] Report sent to {to_email}")
        return True

    except Exception as e:
        print(f"[Email] Failed to send to {to_email}: {e}")
        return False
